name: Dependent Workflow in Project B

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Perform tasks
        run: echo "Workflow in Project B triggered by Project A"
